---
  - name: Connectivity Check Utility
    hosts: test1
    #connection: local
    gather_facts: no
    tasks:

      - name: Check connection
        shell: |
                pwd
                ping -c 4 google.com >> output.txt
                ls -lart
        register: output
      - debug: var=output.stdout_lines
