---
  - name: Connectivity Check Utility
    hosts: ansible_host
    #connection: local
    gather_facts: no
    tasks:

      - name: Check connection
        shell: |
                pwd
                ls -lart
                #ping -c 4 google.com
        register: output
      - debug: var=output.stdout_lines
