---
  - name: Connectivity Check Utility
    hosts: localhost
    connection: local
    gather_facts: no
    tasks:

      - name: Check connection
        shell: |
                ping -c 4 google.com >> /home/ansible/output.txt
        register: output
      - debug: var=output.stdout_lines
